# Generated by Django 3.2.5 on 2022-07-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.TimeField(null=True),
        ),
    ]
