# Generated by Django 3.2.5 on 2022-07-22 11:49

import ckeditor_uploader.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_comment_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLanguage',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(null=True, upload_to='')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created', models.TimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
