# Generated by Django 3.2.5 on 2022-07-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_comment1'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
