# Generated by Django 3.2.5 on 2022-07-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_filesadmin_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlanguage',
            name='adminupload',
            field=models.FileField(default=0, upload_to='media'),
            preserve_default=False,
        ),
    ]
