# Generated by Django 3.2.5 on 2022-07-29 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_projectlanguage_adminupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilesAdmin',
        ),
    ]
