# Generated by Django 3.2.5 on 2022-07-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_delete_filesadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='adminupload',
            field=models.FileField(default=0, upload_to='media'),
            preserve_default=False,
        ),
    ]
