# Generated by Django 3.2.5 on 2022-07-29 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_project_adminupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='adminupload',
        ),
        migrations.RemoveField(
            model_name='projectlanguage',
            name='adminupload',
        ),
    ]
